all.out: testfile.cc disease.cc HeartFailure.cc patient.cc person.cc report.cc
	g++ testfile.cc disease.cc HeartFailure.cc patient.cc person.cc report.cc -lgtest -lgtest_main -lpthread -o all.out 
     
